//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod article_tags;
pub mod articles;
pub mod comments;
pub mod favorites;
pub mod followers;
pub mod tags;
pub mod users;
