//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::article_tags::Entity as ArticleTags;
pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::favorites::Entity as Favorites;
pub use super::followers::Entity as Followers;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
